### ISSUE TITLE
Add css framework

### ISSUE THREAD

**Issue by aaronarduino** [khoyt/weekly-schedule#2]

**Comment by ehoyt1** [comment]
Here are some options:

- Bulma
- PureCSS
- Skeleton

Also, how could we incorporate Sass or Less?

**Comment by aaronarduino** [comment]
I'm sure we could use Sass or Less. But truth be told, I've never used either. lol I need to learn though.

**Comment by aaronarduino** [comment]
After reading up on Sass I think we can certainly use it. 👍
